server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: allgo
          uri: http://localhost:8091/
          predicates:
            - Path=/allgo/**
          filters:
            - name: AllgoFilter
              args:
                baseMessage: Spring Cloud Gateway AllgoFilter
                preLogger: true
                postLogger: true
            - RewritePath=/allgo/(?<apiuri>.*), /${apiuri}
            - PrefixPath=/v1.0
        - id: stock
          uri: http://localhost:8092/
          predicates:
            - Path=/stock/**
          filters:
            - name: StockFilter
              args:
                baseMessage: Spring Cloud Gateway StockFilter
                preLogger: true
                postLogger: true
            - RewritePath=/stock/(?<apiuri>.*), /${apiuri}
            - PrefixPath=/v1.0