spring:
  application:
    name: portfolio-service
  profiles:
    active: dev
  config:
    import: configserver:http://127.0.0.1:8099

management:
  endpoints:
    web:
      exposure:
        include: "*"

