spring:
  application:
    name: allgo-service
  profiles:
    active: test
  config:
    import: configserver:http://1.240.167.231:8099

management:
  endpoints:
    web:
      exposure:
        include: "*"

